INSERT INTO tbl_region values('Main Branch Lahore','0001')
INSERT INTO tbl_region values ('Main Branch Karachi','0002')
INSERT INTO tbl_region values ('Main Branch Peshawar','0003')
INSERT INTO tbl_region values ('Main Branch Quetta','0004')
INSERT INTO tbl_region values ('Main Branch Hyderabad','0006')
INSERT INTO tbl_region values ('Main Branch Gujranwala','0007')
INSERT INTO tbl_region values ('Main Branch Faisalabad','0008')
INSERT INTO tbl_region values ('Small Industrial Estate Branch Sialkot','0009')
INSERT INTO tbl_region values ('Main Branch Gilgit','0010')
INSERT INTO tbl_region values ('Defence Branch Lahore','0011')
INSERT INTO tbl_region values ('Clifton Branch Karachi','0012')
INSERT INTO tbl_region values ('Garden Branch Karachi','0013')
INSERT INTO tbl_region values ('Main Branch Rawalpindi','0014')
INSERT INTO tbl_region values ('Gulberg Branch Lahore','0015')
INSERT INTO tbl_region values ('Main Branch Islamabad','0016')
INSERT INTO tbl_region values ('Main Branch Sheikhupura','0017')
INSERT INTO tbl_region values ('Main Branch Sukkur','0018')
INSERT INTO tbl_region values ('FJR Branch Hyderabad','0019')
INSERT INTO tbl_region values ('FB Area Branch Karachi','0020')
INSERT INTO tbl_region values ('Main Branch Wazirabad','0021')
INSERT INTO tbl_region values ('Main Branch Multan','0022')
INSERT INTO tbl_region values ('Korangi Branch Karachi','0023')
INSERT INTO tbl_region values ('AKU Branch Karachi','0024')
INSERT INTO tbl_region values ('Main Branch Hunza','0025')
INSERT INTO tbl_region values ('Circular Road Branch Lahore','0026')
INSERT INTO tbl_region values ('Haidery Branch Karachi','0027')
INSERT INTO tbl_region values ('Main Branch Sahiwal','0028')
INSERT INTO tbl_region values ('Chowk Yadgar Branch Peshawar','0029')
INSERT INTO tbl_region values ('Jodia Bazar Branch Karachi','0030')
INSERT INTO tbl_region values ('Shahrah e Faisal Branch Karachi','0031')
INSERT INTO tbl_region values ('Defence Branch Karachi','0032')
INSERT INTO tbl_region values ('Main Branch Skardu','0033')
INSERT INTO tbl_region values ('Gulshan-e-Iqbal Branch Karachi','0034')
INSERT INTO tbl_region values ('Model Town Branch Lahore','0035')
INSERT INTO tbl_region values ('Peco Road Branch Lahore','0036')
INSERT INTO tbl_region values ('SITE Branch Karachi','0037')
INSERT INTO tbl_region values ('Zamzama Branch Karachi','0038')
INSERT INTO tbl_region values ('Gole Market Branch Karachi','0039')
INSERT INTO tbl_region values ('Gulistan-e-Jauhar Branch Karachi','0040')
INSERT INTO tbl_region values ('MA Jinnah Road Branch Karachi','0041')
INSERT INTO tbl_region values ('Cavalry Ground Branch Lahore','0042')
INSERT INTO tbl_region values ('Gulbahar Branch Karachi','0043')
INSERT INTO tbl_region values ('North Karachi Branch Karachi','0044')
INSERT INTO tbl_region values ('G9 Markaz Branch Islamabad','0046')
INSERT INTO tbl_region values ('Block 7 Branch Gulshan e Iqbal Karachi','0047')
INSERT INTO tbl_region values ('Islamic Bank-Cloth Market Branch Karachi','0048')
INSERT INTO tbl_region values ('Allama Iqbal Town Branch Lahore','0049')
INSERT INTO tbl_region values ('Paria Street Branch Kharadar Karachi','0050')
INSERT INTO tbl_region values ('Suparco Branch KDA Scheme 33 Karachi','0051')
INSERT INTO tbl_region values ('Chandni Chowk Branch Karachi','0052')
INSERT INTO tbl_region values ('Allama Iqbal Road Branch Karachi','0053')
INSERT INTO tbl_region values ('Chandni Chowk Branch - Rawalpindi','0054')
INSERT INTO tbl_region values ('Baghbanpura Branch Lahore','0055')
INSERT INTO tbl_region values ('Thokar Niaz Baig Branch Lahore','0056')
INSERT INTO tbl_region values ('Nishtar Road Branch Karachi','0057')
INSERT INTO tbl_region values ('Latifabad Branch Hyderabad','0059')
INSERT INTO tbl_region values ('Apwa Complex Branch Karachi','0060')
INSERT INTO tbl_region values ('Ghazi Chowk Branch Lahore','0061')
INSERT INTO tbl_region values ('Main Branch Lodhran','0062')
INSERT INTO tbl_region values ('Clifton Block 2 Branch Karachi','0063')
INSERT INTO tbl_region values ('Islamic Banking New Garden Town Branch LHR','0064')
INSERT INTO tbl_region values ('Malir Branch Karachi','0065')
INSERT INTO tbl_region values ('Bahadurabad Branch Karachi','0066')
INSERT INTO tbl_region values ('New Challi Branch Karachi','0067')
INSERT INTO tbl_region values ('Rahim Yar Khan Branch','0068')
INSERT INTO tbl_region values ('Bahawalpur Branch','0069')
INSERT INTO tbl_region values ('Peoples Colony Branch Faisalabad','0070')
INSERT INTO tbl_region values ('Defence Phase III Branch','0071')
INSERT INTO tbl_region values ('Chungi Amer Sadhu Branch Lahore','0072')
INSERT INTO tbl_region values ('Shah Faisal Colony Branch Karachi','0073')
INSERT INTO tbl_region values ('Zaibunessa Street Branch Karachi','0074')
INSERT INTO tbl_region values ('Johar Town Branch Lahore','0076')
INSERT INTO tbl_region values ('Wahdat Road Branch Lahore','0077')
INSERT INTO tbl_region values ('Islamic Banking Isra University Branch Hyd','0078')
INSERT INTO tbl_region values ('Mansehra Road Branch Abbottabad','0079')
INSERT INTO tbl_region values ('Islamic Banking I 10 Markaz Islamabad','0080')
INSERT INTO tbl_region values ('Okara Branch','0081')
INSERT INTO tbl_region values ('Gahkuch Branch','0082')
INSERT INTO tbl_region values ('Liaquatabad Branch Karachi','0083')
INSERT INTO tbl_region values ('Lea Market Branch Karachi','0084')
INSERT INTO tbl_region values ('Korangi Township No 3 Branch Karachi','0085')
INSERT INTO tbl_region values ('Sadiqabad Branch','0086')
INSERT INTO tbl_region values ('Sargodha Branch','0087')
INSERT INTO tbl_region values ('Gunpat Road Branch Lahore','0088')
INSERT INTO tbl_region values ('North Karachi Industrial Area Branch','0090')
INSERT INTO tbl_region values ('Hub Branch Distt. Lasbela','0091')
INSERT INTO tbl_region values ('F B Industrial Area Branch','0092')
INSERT INTO tbl_region values ('Airport Road Branch','0093')
INSERT INTO tbl_region values ('Golarchi Branch Distt Badin','0094')
INSERT INTO tbl_region values ('Buhara Branch Distt Thatta','0095')
INSERT INTO tbl_region values ('Gujar Khan Branch','0096')
INSERT INTO tbl_region values ('Napier Road Branch','0098')
INSERT INTO tbl_region values ('Ravi Road Branch Lahore','0099')
INSERT INTO tbl_region values ('Shahdra Branch Lahore','0100')
INSERT INTO tbl_region values ('Jhelum Branch','0101')
INSERT INTO tbl_region values ('Manga Mandi Branch Lahore','0102')
INSERT INTO tbl_region values ('Badian Road Branch Lahore','0103')
INSERT INTO tbl_region values ('Mughalpura Branch Lahore','0104')
INSERT INTO tbl_region values ('Bosan Road Branch Multan','0105')
INSERT INTO tbl_region values ('Gulshan-e-Hadeed Branch Karachi','0106')
INSERT INTO tbl_region values ('Khanewal Branch','0107')
INSERT INTO tbl_region values ('Islamic Banking Khyber Bazar BR Peshawar','0108')
INSERT INTO tbl_region values ('Burewala Branch','0109')
INSERT INTO tbl_region values ('Metroville Branch Karachi','0111')
INSERT INTO tbl_region values ('Prince Ali Road Branch Hyderabad','0112')
INSERT INTO tbl_region values ('Defence Phase-II Extn. Branch Karachi','0114')
INSERT INTO tbl_region values ('North Karachi Township Branch Karachi','0115')
INSERT INTO tbl_region values ('Hafizabad Branch','0116')
INSERT INTO tbl_region values ('Islamic Banking Shahrah-e-Iqbal Branch QTA','0117')
INSERT INTO tbl_region values ('Waisa Branch Tehsil Hazro District Attock','0118')
INSERT INTO tbl_region values ('Karachi Stock Exchange Branch Karachi','0120')
INSERT INTO tbl_region values ('Upper Mall Road Branch Lahore','0121')
INSERT INTO tbl_region values ('I - 9 Markaz Branch Islamabad','0122')
INSERT INTO tbl_region values ('22 Number Chungi Branch Rawalpindi','0123')
INSERT INTO tbl_region values ('Islampura Krishan Nagar Branch Lahore','0124')
INSERT INTO tbl_region values ('Talhar Branch District Badin','0125')
INSERT INTO tbl_region values ('Gulshan-e-Jamal Branch Karachi','0126')
INSERT INTO tbl_region values ('Muslim Town  Branch Rawalpindi','0127')
INSERT INTO tbl_region values ('Danyore Branch District Gilgit','0129')
INSERT INTO tbl_region values ('Pasrur Road Branch Sialkot','0130')
INSERT INTO tbl_region values ('Alyabad Branch Karachi','0131')
INSERT INTO tbl_region values ('Depalpur Br. Distt. Okara','0132')
INSERT INTO tbl_region values ('Kharoor Pacca Br. Distt. Lodhran','0133')
INSERT INTO tbl_region values ('Muzafargarh Br. Distt. Muzafargarh','0134')
INSERT INTO tbl_region values ('Saudabad Br. Malir Karachi','0135')
INSERT INTO tbl_region values ('Shireen Jinnah Colony Br Karachi','0136')
INSERT INTO tbl_region values ('E-11 Branch Islamabad','0137')
INSERT INTO tbl_region values ('Kharian Branch District Gujrat','0138')
INSERT INTO tbl_region values ('Shahbaz Khan Road Branch Kasur','0139')
INSERT INTO tbl_region values ('Mian Channu Branch','0140')
INSERT INTO tbl_region values ('Ghulam Muhammadabad Branch Faisalabad','0141')
INSERT INTO tbl_region values ('Pattoki Branch','0142')
INSERT INTO tbl_region values ('Nankana Sahib Branch','0143')
INSERT INTO tbl_region values ('Chitral Main Branch','0145')
INSERT INTO tbl_region values ('Pindora Branch','0146')
INSERT INTO tbl_region values ('Tando Allah Yar Branch Distt Tando AllahYar','0147')
INSERT INTO tbl_region values ('Sultanabad Branch District Tando AllahYar','0148')
INSERT INTO tbl_region values ('Sanghar Branch District Sanghar','0149')
INSERT INTO tbl_region values ('Deh. Sonhar Branch District Badin','0151')
INSERT INTO tbl_region values ('Matyari Branch District Matyari','0154')
INSERT INTO tbl_region values ('Barkat-e-Haidery Branch Karachi','0155')
INSERT INTO tbl_region values ('Garhi Shahu Branch Lahore','0156')
INSERT INTO tbl_region values ('Shadman Town Branch Karachi','0157')
INSERT INTO tbl_region values ('Zarrar Shaheed Road Branch Lahore','0158')
INSERT INTO tbl_region values ('Bewal Branch Gujjar Khan','0159')
INSERT INTO tbl_region values ('Bahawalnagar Branch','0161')
INSERT INTO tbl_region values ('Liaqatpur Branch','0162')
INSERT INTO tbl_region values ('Chakwal Branch Distt. Chakwal','0163')
INSERT INTO tbl_region values ('SITE Branch Hyderabad','0165')
INSERT INTO tbl_region values ('Sambrial Branch Distt. Sialkot','0166')
INSERT INTO tbl_region values ('Ghakkar Mandi Branch Distt. Gujranwala','0168')
INSERT INTO tbl_region values ('Matli District Badin','0169')
INSERT INTO tbl_region values ('Fazal Garh Sanawan Br. Distt. Muzafargarh','0170')
INSERT INTO tbl_region values ('Gujrat Branch','0171')
INSERT INTO tbl_region values ('Hamdard Chowk Kot Lakhpat Branch Lahore','0172')
INSERT INTO tbl_region values ('Kana Kacha Branch Lahore','0173')
INSERT INTO tbl_region values ('Gulraiz Branch Rawalpindi','0174')
INSERT INTO tbl_region values ('Lathrar Road Branch Tarlai Distt. Islamabad','0175')
INSERT INTO tbl_region values ('DHA Phase-II Branch Islamabad','0176')
INSERT INTO tbl_region values ('Jutial Branch Distt. Gilgit','0177')
INSERT INTO tbl_region values ('Enquiry Office Nazimabad No. 2 Branch Khi','0178')
INSERT INTO tbl_region values ('Block 13 - D Gulshan-e-Iqbal Branch Khi','0179')
INSERT INTO tbl_region values ('Faqir Jo Pir Branch Hyderabad','0180')
INSERT INTO tbl_region values ('Tando Bago Branch Distt. Badin','0181')
INSERT INTO tbl_region values ('Nawabshah Branch','0182')
INSERT INTO tbl_region values ('Umerkot Branch','0183')
INSERT INTO tbl_region values ('Shahdadpur Branch Distt. Sanghar','0184')
INSERT INTO tbl_region values ('Timber Market Branch Karachi','0185')
INSERT INTO tbl_region values ('Soan Garden Br. Lohi Bheer Distt. Islamabad','0186')
INSERT INTO tbl_region values ('Mardan Branch Distt Mardan','0189')
INSERT INTO tbl_region values ('Azmat Road Branch Dera Ghazi Khan','0190')
INSERT INTO tbl_region values ('Jaranwala Branch Distt. Faisalabad','0191')
INSERT INTO tbl_region values ('Jhang Branch','0192')
INSERT INTO tbl_region values ('Chiniot Branch','0193')
INSERT INTO tbl_region values ('Sabzazar Branch Multan Road Lahore','0195')
INSERT INTO tbl_region values ('Haroonabad Branch Distt Bahawalnagar','0196')
INSERT INTO tbl_region values ('Mirpurkhas Branch','0197')
INSERT INTO tbl_region values ('Mailsi Branch Distt Vehari','0198')
INSERT INTO tbl_region values ('Mumtazabad Branch Multan','0201')
INSERT INTO tbl_region values ('Kamoke Branch Distt. Gujranwala','0202')
INSERT INTO tbl_region values ('Sheikhoo Sugar Mills Kot Addu Distt. Muzaf','0203')
INSERT INTO tbl_region values ('Islamic Banking F-8 Markaz Branch Islamabad','0205')
INSERT INTO tbl_region values ('Khayaban-e-Ittehad DHA Phase-VI Branch Khi','0206')
INSERT INTO tbl_region values ('Qasimabad Branch Hyderabad','0208')
INSERT INTO tbl_region values ('Panjhatti Branch, Distt. Khairpur','0209')
INSERT INTO tbl_region values ('Main Branch Larkana','0210')
INSERT INTO tbl_region values ('DHA Phase-IV Branch Lahore','0211')
INSERT INTO tbl_region values ('Kabirwala Branch distt. Khanewal','0212')
INSERT INTO tbl_region values ('Muzaffarabad Branch','0213')
INSERT INTO tbl_region values ('Azam Cloth Market Branch Lahore','0214')
INSERT INTO tbl_region values ('Jail Road Branch Lahore','0215')
INSERT INTO tbl_region values ('Badami Bagh Branch Lahore','0217')
INSERT INTO tbl_region values ('Gojra Branch Distt. Toba Tek Singh','0218')
INSERT INTO tbl_region values ('Gagoo Mandi Branch Distt. Vehari','0219')
INSERT INTO tbl_region values ('Mandi Bahauddin Branch','0220')
INSERT INTO tbl_region values ('Samundri Branch Distt. Faisalabad','0221')
INSERT INTO tbl_region values ('Kamalia Branch Distt. Toba Tek Singh','0222')
INSERT INTO tbl_region values ('Wapda Town Branch Gujranwala','0223')
INSERT INTO tbl_region values ('G-11 Markaz Branch Islamabad','0224')
INSERT INTO tbl_region values ('Chicha Watni Branch','0226')
INSERT INTO tbl_region values ('Daska Branch','0227')
INSERT INTO tbl_region values ('Godhpur Branch','0228')
INSERT INTO tbl_region values ('Toba Tek Singh','0229')
INSERT INTO tbl_region values ('Ghotki Branch','0230')
INSERT INTO tbl_region values ('Tando Adam Branch Distt. Sanghar','0231')
INSERT INTO tbl_region values ('Islamic Banking Chillas Branch Dist. Diamer','0232')
INSERT INTO tbl_region values ('Layyah Branch','0234')
INSERT INTO tbl_region values ('Hasilpur Branch','0235')
INSERT INTO tbl_region values ('Muridke Branch','0236')
INSERT INTO tbl_region values ('Islamic Banking Waterpump Karachi','0237')
INSERT INTO tbl_region values ('Deharki Branch','0238')
INSERT INTO tbl_region values ('Thull Branch','0239')
INSERT INTO tbl_region values ('Kandkhot Branch','0240')
INSERT INTO tbl_region values ('Islamic Banking East Canal Rd Br.Faisalabad','0241')
INSERT INTO tbl_region values ('Islamic Banking Sialkot Cantt. Br. Sialkot','0242')
INSERT INTO tbl_region values ('Islamic Banking Al-Tijarah Centre Br. Kar.','0243')
INSERT INTO tbl_region values ('Islamic Banking Temple Road Branch Lahore','0244')
INSERT INTO tbl_region values ('Islamic Banking Shah Rukn-e-Alam Br. Multan','0245')
INSERT INTO tbl_region values ('Islamic Banking Peshawar Road Br Rawalpindi','0246')
INSERT INTO tbl_region values ('Montgomery Road Branch Lahore','0247')
INSERT INTO tbl_region values ('Bahria Complex-III Branch Karachi','0249')
INSERT INTO tbl_region values ('Jalal Pur Bhattian Branch','0251')
INSERT INTO tbl_region values ('Bahria Town Branch','0252')
INSERT INTO tbl_region values ('Arifwala Branch','0253')
INSERT INTO tbl_region values ('Pak Pattan Branch','0254')
INSERT INTO tbl_region values ('Jacobabad Branch','0255')
INSERT INTO tbl_region values ('Painsera Branch','0256')
INSERT INTO tbl_region values ('Shahdadkot Branch','0257')
INSERT INTO tbl_region values ('Abdul Hakeem Branch','0258')
INSERT INTO tbl_region values ('Expo Centre Branch H Block Lahore','0259')
INSERT INTO tbl_region values ('Bahria Town Branch Rawalpindi','0260')
INSERT INTO tbl_region values ('Wapda Town Branch Lahore','0261')
INSERT INTO tbl_region values ('New M. A. Jinnah Road Branch','0262')
INSERT INTO tbl_region values ('Ellahabad Branch','0263')
INSERT INTO tbl_region values ('Pir Mahal Branch Distt. Toba Tek Singh','0264')
INSERT INTO tbl_region values ('Shah Alam Market, Lahore','0265')
INSERT INTO tbl_region values ('Islamic Banking Mingora Branch','0266')
INSERT INTO tbl_region values ('DHA Phase IV Karachi','0267')
INSERT INTO tbl_region values ('Tando Muhammad Khan','0268' )
INSERT INTO tbl_region values ('F-11 Markaz Branch, Islamabad','0269')
INSERT INTO tbl_region values ('Gulberg Branch, Federal B Area, Karachi','0270')
INSERT INTO tbl_region values ('Civil Lines Branch, Faisalabad','0271')
INSERT INTO tbl_region values ('Chamman','0272')
INSERT INTO tbl_region values ('Khurrianwala Branch Distt. Faisalabad','0273')
INSERT INTO tbl_region values ('Dadu','0274')
INSERT INTO tbl_region values ('Shikarpur','0275')
INSERT INTO tbl_region values ('Chishtian','0276')
INSERT INTO tbl_region values ('Khanpur','0277')
INSERT INTO tbl_region values ('Khudian','0278')
INSERT INTO tbl_region values ('Auto Bhan Road Branch','0279')
INSERT INTO tbl_region values ('DHA Phase-V Branch','0280')
INSERT INTO tbl_region values ('Chauburji Branch, Lahore','0281')
INSERT INTO tbl_region values ('Narowal Branch','0282')
INSERT INTO tbl_region values ('Haveli Lakha Branch','0283')
INSERT INTO tbl_region values ('Mansehra Branch','0284')
INSERT INTO tbl_region values ('Bhalwal Branch','0285')
INSERT INTO tbl_region values ('Walton Road Branch','0286')
INSERT INTO tbl_region values ('Faisal Town Branch','0287')
INSERT INTO tbl_region values ('Battagram Branch','0288')
INSERT INTO tbl_region values ('F-6 Branch Islamabad','0289')
INSERT INTO tbl_region values ('Rajanpur Branch','0290')
INSERT INTO tbl_region values ('Gulgasht Colony Branch Multan','0291')
INSERT INTO tbl_region values ('Ahmedpur Sharqia Branch','0292')
INSERT INTO tbl_region values ('Chowk Azam Branch','0293')
INSERT INTO tbl_region values ('Karim Block Branch, Lahore','0294')
INSERT INTO tbl_region values ('New Sabzi Mandi Branch, Karachi','0295')
INSERT INTO tbl_region values ('Clifton Block-08 Branch, Karachi','0296')
INSERT INTO tbl_region values ('Defence Road Branch, Lahore','0297')
INSERT INTO tbl_region values ('Hujra Shah Muqeem Branch','0298')
INSERT INTO tbl_region values ('Block-02 Gulshan-e-Iqbal Branch, Karachi','0299')
INSERT INTO tbl_region values ('Marriot Road Branch, Karachi','0300')
INSERT INTO tbl_region values ('Garden Market Branch, Karachi','0301')
INSERT INTO tbl_region values ('Block-N North Nazimabad Branch, Karachi','0302')
INSERT INTO tbl_region values ('Pull-111 Branch, Sargodha','0303')
INSERT INTO tbl_region values ('PWD Branch Islamabad','0304')
INSERT INTO tbl_region values ('Wapda Town Branch, Multan','0305')
INSERT INTO tbl_region values ('Gulshan-e-Maymar Branch, Karachi','0306')
INSERT INTO tbl_region values ('Islamic Banking DHA Phase-VI Branch, Lahore','0307')
INSERT INTO tbl_region values ('Islamic Banking Gujranwala Cantt. Branch','0308')
INSERT INTO tbl_region values ('Islamic Banking Swabi Branch','0309')
INSERT INTO tbl_region values ('Madina Town Branch, Faisalabad','0310')
INSERT INTO tbl_region values ('Khuzdar Branch, Tehsil Khuzdar','0311')
INSERT INTO tbl_region values ('Gawadar Branch, Tehsil & District Gawadar','0312')
INSERT INTO tbl_region values ('Shersha Branch, Karachi','0313')
INSERT INTO tbl_region values ('Kohat Branch, District Kohat','0314')
INSERT INTO tbl_region values ('Safari Garden Branch, Sue-e-Asal Road Lahore','0315')
INSERT INTO tbl_region values ('Dhabeji Branch, District Thatta','0316')


INSERT INTO tbl_region values ('Main Branch Mirpur','0005')
INSERT INTO tbl_region values ('Islamgarh Branch Mirpur','0097')
INSERT INTO tbl_region values ('Jatlan Branch District Mirpur','0153')