//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CardIssuanceSystem.NewCISSB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="T24WebServicesImplPortBinding", Namespace="http://temenos.com/SON.CARD.OPS")]
    public partial class T24WebServicesImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CARDOPSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public T24WebServicesImplService() {
            this.Url = global::CardIssuanceSystem.Properties.Settings.Default.CardIssuanceSystem_NewCISSB_T24WebServicesImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CARDOPSCompletedEventHandler CARDOPSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://temenos.com/SON.CARD.OPS", ResponseNamespace="http://temenos.com/SON.CARD.OPS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Status CARDOPS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] webRequestCommon WebRequestCommon, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] enquiryInputCollection[] SONFETCHCARDINFOType, [System.Xml.Serialization.XmlElementAttribute("SONFETCHCARDINFOType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out SONFETCHCARDINFOType[] SONFETCHCARDINFOType1) {
            object[] results = this.Invoke("CARDOPS", new object[] {
                        WebRequestCommon,
                        SONFETCHCARDINFOType});
            SONFETCHCARDINFOType1 = ((SONFETCHCARDINFOType[])(results[1]));
            return ((Status)(results[0]));
        }
        
        /// <remarks/>
        public void CARDOPSAsync(webRequestCommon WebRequestCommon, enquiryInputCollection[] SONFETCHCARDINFOType) {
            this.CARDOPSAsync(WebRequestCommon, SONFETCHCARDINFOType, null);
        }
        
        /// <remarks/>
        public void CARDOPSAsync(webRequestCommon WebRequestCommon, enquiryInputCollection[] SONFETCHCARDINFOType, object userState) {
            if ((this.CARDOPSOperationCompleted == null)) {
                this.CARDOPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCARDOPSOperationCompleted);
            }
            this.InvokeAsync("CARDOPS", new object[] {
                        WebRequestCommon,
                        SONFETCHCARDINFOType}, this.CARDOPSOperationCompleted, userState);
        }
        
        private void OnCARDOPSOperationCompleted(object arg) {
            if ((this.CARDOPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CARDOPSCompleted(this, new CARDOPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://temenos.com/SON.CARD.OPS")]
    public partial class webRequestCommon {
        
        private string companyField;
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://temenos.com/SONFETCHCARDINFO")]
    public partial class SONFETCHCARDINFOType {
        
        private string aCCTIDField;
        
        private SONFETCHCARDINFOTypeGSONFETCHCARDINFODetailType gSONFETCHCARDINFODetailTypeField;
        
        /// <remarks/>
        public string ACCTID {
            get {
                return this.aCCTIDField;
            }
            set {
                this.aCCTIDField = value;
            }
        }
        
        /// <remarks/>
        public SONFETCHCARDINFOTypeGSONFETCHCARDINFODetailType gSONFETCHCARDINFODetailType {
            get {
                return this.gSONFETCHCARDINFODetailTypeField;
            }
            set {
                this.gSONFETCHCARDINFODetailTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://temenos.com/SONFETCHCARDINFO")]
    public partial class SONFETCHCARDINFOTypeGSONFETCHCARDINFODetailType {
        
        private SONFETCHCARDINFOTypeGSONFETCHCARDINFODetailTypeMSONFETCHCARDINFODetailType[] mSONFETCHCARDINFODetailTypeField;
        
        private string gField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mSONFETCHCARDINFODetailType")]
        public SONFETCHCARDINFOTypeGSONFETCHCARDINFODetailTypeMSONFETCHCARDINFODetailType[] mSONFETCHCARDINFODetailType {
            get {
                return this.mSONFETCHCARDINFODetailTypeField;
            }
            set {
                this.mSONFETCHCARDINFODetailTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string g {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://temenos.com/SONFETCHCARDINFO")]
    public partial class SONFETCHCARDINFOTypeGSONFETCHCARDINFODetailTypeMSONFETCHCARDINFODetailType {
        
        private string accountIDField;
        
        private string customerField;
        
        private string hDR1Field;
        
        private string customerIDField;
        
        private string customerNameField;
        
        private string sectorField;
        
        private string customerDOBField;
        
        private string fathersNameField;
        
        private string mothersNameField;
        
        private string nationalityField;
        
        private string genderField;
        
        private string identificationNoField;
        
        private string identificationTypeField;
        
        private string offPhoneField;
        
        private string accountMobileField;
        
        private string sMSField;
        
        private string emailField;
        
        private string accountCurrencyField;
        
        private string postingRestrictionField;
        
        private string errorFieldField;
        
        private string branchCodeField;
        
        private string branchNameField;
        
        private string accountTitleField;
        
        private string t24ACNOField;
        
        private string passportField;
        
        private string phoneResidenceField;
        
        private string customerAddress1Field;
        
        private string accountAddressField;
        
        private string availableBalanceField;
        
        private string residenceStatusField;
        
        private string productField;
        
        private string categoryField;
        
        private string accountNatureField;
        
        private string accountStatusField;
        
        private string customerAddress2Field;
        
        private string sMS2Field;
        
        private string sMS3Field;
        
        private string sUBSCRIPTIONField;
        
        private string rEGISTERNUMBERField;
        
        private string opInstructionsField;
        
        private string mField;
        
        /// <remarks/>
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public string HDR1 {
            get {
                return this.hDR1Field;
            }
            set {
                this.hDR1Field = value;
            }
        }
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerDOB {
            get {
                return this.customerDOBField;
            }
            set {
                this.customerDOBField = value;
            }
        }
        
        /// <remarks/>
        public string FathersName {
            get {
                return this.fathersNameField;
            }
            set {
                this.fathersNameField = value;
            }
        }
        
        /// <remarks/>
        public string MothersName {
            get {
                return this.mothersNameField;
            }
            set {
                this.mothersNameField = value;
            }
        }
        
        /// <remarks/>
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string IdentificationNo {
            get {
                return this.identificationNoField;
            }
            set {
                this.identificationNoField = value;
            }
        }
        
        /// <remarks/>
        public string IdentificationType {
            get {
                return this.identificationTypeField;
            }
            set {
                this.identificationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OffPhone {
            get {
                return this.offPhoneField;
            }
            set {
                this.offPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string AccountMobile {
            get {
                return this.accountMobileField;
            }
            set {
                this.accountMobileField = value;
            }
        }
        
        /// <remarks/>
        public string SMS {
            get {
                return this.sMSField;
            }
            set {
                this.sMSField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCurrency {
            get {
                return this.accountCurrencyField;
            }
            set {
                this.accountCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string PostingRestriction {
            get {
                return this.postingRestrictionField;
            }
            set {
                this.postingRestrictionField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorField {
            get {
                return this.errorFieldField;
            }
            set {
                this.errorFieldField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountTitle {
            get {
                return this.accountTitleField;
            }
            set {
                this.accountTitleField = value;
            }
        }
        
        /// <remarks/>
        public string T24ACNO {
            get {
                return this.t24ACNOField;
            }
            set {
                this.t24ACNOField = value;
            }
        }
        
        /// <remarks/>
        public string Passport {
            get {
                return this.passportField;
            }
            set {
                this.passportField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneResidence {
            get {
                return this.phoneResidenceField;
            }
            set {
                this.phoneResidenceField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerAddress1 {
            get {
                return this.customerAddress1Field;
            }
            set {
                this.customerAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string AccountAddress {
            get {
                return this.accountAddressField;
            }
            set {
                this.accountAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AvailableBalance {
            get {
                return this.availableBalanceField;
            }
            set {
                this.availableBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string ResidenceStatus {
            get {
                return this.residenceStatusField;
            }
            set {
                this.residenceStatusField = value;
            }
        }
        
        /// <remarks/>
        public string Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNature {
            get {
                return this.accountNatureField;
            }
            set {
                this.accountNatureField = value;
            }
        }
        
        /// <remarks/>
        public string AccountStatus {
            get {
                return this.accountStatusField;
            }
            set {
                this.accountStatusField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerAddress2 {
            get {
                return this.customerAddress2Field;
            }
            set {
                this.customerAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string SMS2 {
            get {
                return this.sMS2Field;
            }
            set {
                this.sMS2Field = value;
            }
        }
        
        /// <remarks/>
        public string SMS3 {
            get {
                return this.sMS3Field;
            }
            set {
                this.sMS3Field = value;
            }
        }
        
        /// <remarks/>
        public string SUBSCRIPTION {
            get {
                return this.sUBSCRIPTIONField;
            }
            set {
                this.sUBSCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        public string REGISTERNUMBER {
            get {
                return this.rEGISTERNUMBERField;
            }
            set {
                this.rEGISTERNUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string OpInstructions {
            get {
                return this.opInstructionsField;
            }
            set {
                this.opInstructionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string m {
            get {
                return this.mField;
            }
            set {
                this.mField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://temenos.com/SON.CARD.OPS")]
    public partial class Status {
        
        private string transactionIdField;
        
        private string messageIdField;
        
        private successIndicator successIndicatorField;
        
        private bool successIndicatorFieldSpecified;
        
        private string applicationField;
        
        private string[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public successIndicator successIndicator {
            get {
                return this.successIndicatorField;
            }
            set {
                this.successIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successIndicatorSpecified {
            get {
                return this.successIndicatorFieldSpecified;
            }
            set {
                this.successIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://temenos.com/SON.CARD.OPS")]
    public enum successIndicator {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        TWSError,
        
        /// <remarks/>
        T24Error,
        
        /// <remarks/>
        T24Override,
        
        /// <remarks/>
        T24Offline,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://temenos.com/SON.CARD.OPS")]
    public partial class enquiryInputCollection {
        
        private string columnNameField;
        
        private string criteriaValueField;
        
        private string operandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string columnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string criteriaValue {
            get {
                return this.criteriaValueField;
            }
            set {
                this.criteriaValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operand {
            get {
                return this.operandField;
            }
            set {
                this.operandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CARDOPSCompletedEventHandler(object sender, CARDOPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CARDOPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CARDOPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Status Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public SONFETCHCARDINFOType[] SONFETCHCARDINFOType1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SONFETCHCARDINFOType[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591