//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIssuanceSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_File_Exports
    {
        public int ID { get; set; }
        public string CardTypes { get; set; }
        public string BranchCodes { get; set; }
        public string RequestTypes { get; set; }
        public Nullable<long> RecordCount { get; set; }
    }
}
