//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIssuanceSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IncomeAccounts
    {
        public int ID { get; set; }
        public string AccountType { get; set; }
        public string CodeGL { get; set; }
        public string AccountMapping { get; set; }
        public string Classification { get; set; }
        public string TakeOn { get; set; }
        public string Category { get; set; }
        public string InternalAccount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string DescriptionGL { get; set; }
    }
}
