//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIssuanceSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer_Cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer_Cards()
        {
            this.tbl_Card_Charges_Recovery = new HashSet<tbl_Card_Charges_Recovery>();
        }
    
        public long ID { get; set; }
        public string CardNo { get; set; }
        public Nullable<bool> CardStatusActive { get; set; }
        public Nullable<int> CardTypeID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<bool> WaiveCharges { get; set; }
        public string Salutation { get; set; }
        public string CardTitle { get; set; }
        public Nullable<System.DateTime> CardExpiry { get; set; }
        public Nullable<System.DateTime> CardIssuance { get; set; }
        public string CIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Card_Charges_Recovery> tbl_Card_Charges_Recovery { get; set; }
    }
}
