//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIssuanceSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Card_Charges_Recovery
    {
        public int ID { get; set; }
        public Nullable<long> CardID { get; set; }
        public Nullable<System.DateTime> ApplicableDate { get; set; }
        public Nullable<int> CardChargesID { get; set; }
        public Nullable<double> ApplicableAmount { get; set; }
        public Nullable<double> DeducatedAmount { get; set; }
        public Nullable<System.DateTime> LastDeducationDate { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> Regional_Charges_ID { get; set; }
        public string AccountNo { get; set; }
        public string AccountCode { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public string ChargesDescription { get; set; }
        public string CIF { get; set; }
    
        public virtual tbl_Customer_Cards tbl_Customer_Cards { get; set; }
    }
}
