//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIssuanceSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transactions
    {
        public long ID { get; set; }
        public string Narration { get; set; }
        public Nullable<double> Amount { get; set; }
        public string DebitAccountNo { get; set; }
        public string CreditAccountNo { get; set; }
        public string RequestType { get; set; }
        public string STAN { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseCodeDescription { get; set; }
        public string BranchCode { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public string TransactionIdNo { get; set; }
        public string TransactionRefNo { get; set; }
    }
}
