//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIssuanceSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Card_Upgrade_Types
    {
        public int ID { get; set; }
        public Nullable<int> ParentCardType { get; set; }
        public Nullable<int> ChildCardType { get; set; }
    
        public virtual tbl_Card_Types tbl_Card_Types { get; set; }
        public virtual tbl_Card_Types tbl_Card_Types1 { get; set; }
    }
}
