//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIssuanceSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Card_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Card_Types()
        {
            this.tbl_Card_Charges = new HashSet<tbl_Card_Charges>();
            this.tbl_Card_Upgrade_Types = new HashSet<tbl_Card_Upgrade_Types>();
            this.tbl_Card_Upgrade_Types1 = new HashSet<tbl_Card_Upgrade_Types>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AuthorizationStatus { get; set; }
        public string AuthorizationComments { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CardCode { get; set; }
        public Nullable<bool> IsIssuance { get; set; }
        public Nullable<bool> IsReplacement { get; set; }
        public Nullable<bool> IsUpgrade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Card_Charges> tbl_Card_Charges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Card_Upgrade_Types> tbl_Card_Upgrade_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Card_Upgrade_Types> tbl_Card_Upgrade_Types1 { get; set; }
    }
}
