//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIssuanceSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Profile
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AuthorizationStatus { get; set; }
        public string AuthorizationComments { get; set; }
    }
}
