//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIssuanceSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User_Log
    {
        public long ID { get; set; }
        public string EventName { get; set; }
        public string EntityName { get; set; }
        public Nullable<long> EntityID { get; set; }
        public Nullable<System.DateTime> ActionTimestamp { get; set; }
        public Nullable<int> ActionUserStamp { get; set; }
        public string Descp { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
