//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CardIssuanceSystem.CISSB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TestService", Namespace="http://tempuri.org/")]
    public partial class BEAPITransactionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private BEAPIAuthHeader bEAPIAuthHeaderValueField;
        
        private System.Threading.SendOrPostCallback FetchAccountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEODStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatementTodayOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BEAPITransactionService() {
            this.Url = global::CardIssuanceSystem.Properties.Settings.Default.CardIssuanceSystem_CISSB_BEAPITransactionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public BEAPIAuthHeader BEAPIAuthHeaderValue {
            get {
                return this.bEAPIAuthHeaderValueField;
            }
            set {
                this.bEAPIAuthHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FetchAccountInfoCompletedEventHandler FetchAccountInfoCompleted;
        
        /// <remarks/>
        public event GetEODStatusCompletedEventHandler GetEODStatusCompleted;
        
        /// <remarks/>
        public event DoTransactionsCompletedEventHandler DoTransactionsCompleted;
        
        /// <remarks/>
        public event GetTransactionStatusCompletedEventHandler GetTransactionStatusCompleted;
        
        /// <remarks/>
        public event GetStatementTodayCompletedEventHandler GetStatementTodayCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BEAPIAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchAccountInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AccountInfoResponse FetchAccountInfo(AccountInfoRequest AcntInfoRequest) {
            object[] results = this.Invoke("FetchAccountInfo", new object[] {
                        AcntInfoRequest});
            return ((AccountInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void FetchAccountInfoAsync(AccountInfoRequest AcntInfoRequest) {
            this.FetchAccountInfoAsync(AcntInfoRequest, null);
        }
        
        /// <remarks/>
        public void FetchAccountInfoAsync(AccountInfoRequest AcntInfoRequest, object userState) {
            if ((this.FetchAccountInfoOperationCompleted == null)) {
                this.FetchAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchAccountInfoOperationCompleted);
            }
            this.InvokeAsync("FetchAccountInfo", new object[] {
                        AcntInfoRequest}, this.FetchAccountInfoOperationCompleted, userState);
        }
        
        private void OnFetchAccountInfoOperationCompleted(object arg) {
            if ((this.FetchAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchAccountInfoCompleted(this, new FetchAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BEAPIAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEODStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EODStatusReponse GetEODStatus() {
            object[] results = this.Invoke("GetEODStatus", new object[0]);
            return ((EODStatusReponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetEODStatusAsync() {
            this.GetEODStatusAsync(null);
        }
        
        /// <remarks/>
        public void GetEODStatusAsync(object userState) {
            if ((this.GetEODStatusOperationCompleted == null)) {
                this.GetEODStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEODStatusOperationCompleted);
            }
            this.InvokeAsync("GetEODStatus", new object[0], this.GetEODStatusOperationCompleted, userState);
        }
        
        private void OnGetEODStatusOperationCompleted(object arg) {
            if ((this.GetEODStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEODStatusCompleted(this, new GetEODStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BEAPIAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DoTransactions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransactionInfoResponse DoTransactions(TransactionInfoRequest CreateTranRequest) {
            object[] results = this.Invoke("DoTransactions", new object[] {
                        CreateTranRequest});
            return ((TransactionInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DoTransactionsAsync(TransactionInfoRequest CreateTranRequest) {
            this.DoTransactionsAsync(CreateTranRequest, null);
        }
        
        /// <remarks/>
        public void DoTransactionsAsync(TransactionInfoRequest CreateTranRequest, object userState) {
            if ((this.DoTransactionsOperationCompleted == null)) {
                this.DoTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoTransactionsOperationCompleted);
            }
            this.InvokeAsync("DoTransactions", new object[] {
                        CreateTranRequest}, this.DoTransactionsOperationCompleted, userState);
        }
        
        private void OnDoTransactionsOperationCompleted(object arg) {
            if ((this.DoTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoTransactionsCompleted(this, new DoTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BEAPIAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransactionStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransactionStatusResponse GetTransactionStatus(TransactionStatusRequest CreateTranStatusRequest) {
            object[] results = this.Invoke("GetTransactionStatus", new object[] {
                        CreateTranStatusRequest});
            return ((TransactionStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionStatusAsync(TransactionStatusRequest CreateTranStatusRequest) {
            this.GetTransactionStatusAsync(CreateTranStatusRequest, null);
        }
        
        /// <remarks/>
        public void GetTransactionStatusAsync(TransactionStatusRequest CreateTranStatusRequest, object userState) {
            if ((this.GetTransactionStatusOperationCompleted == null)) {
                this.GetTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("GetTransactionStatus", new object[] {
                        CreateTranStatusRequest}, this.GetTransactionStatusOperationCompleted, userState);
        }
        
        private void OnGetTransactionStatusOperationCompleted(object arg) {
            if ((this.GetTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionStatusCompleted(this, new GetTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("BEAPIAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStatementToday", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetStatementTodayResponse", Namespace="http://tempuri.org/")]
        public GetStatementTodayResponse GetStatementToday([System.Xml.Serialization.XmlElementAttribute("GetStatementToday", Namespace="http://tempuri.org/")] GetStatementToday GetStatementToday1) {
            object[] results = this.Invoke("GetStatementToday", new object[] {
                        GetStatementToday1});
            return ((GetStatementTodayResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatementTodayAsync(GetStatementToday GetStatementToday1) {
            this.GetStatementTodayAsync(GetStatementToday1, null);
        }
        
        /// <remarks/>
        public void GetStatementTodayAsync(GetStatementToday GetStatementToday1, object userState) {
            if ((this.GetStatementTodayOperationCompleted == null)) {
                this.GetStatementTodayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatementTodayOperationCompleted);
            }
            this.InvokeAsync("GetStatementToday", new object[] {
                        GetStatementToday1}, this.GetStatementTodayOperationCompleted, userState);
        }
        
        private void OnGetStatementTodayOperationCompleted(object arg) {
            if ((this.GetStatementTodayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatementTodayCompleted(this, new GetStatementTodayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class BEAPIAuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string systemCodeField;
        
        private string userIDField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string SystemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SONTXNSTODAYLISTType {
        
        private string responseCodeField;
        
        private string responseCodeDescriptionField;
        
        private SONTXNSTODAYLISTTypeGSONTXNSTODAYLISTDetailType gSONTXNSTODAYLISTDetailTypeField;
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeDescription {
            get {
                return this.responseCodeDescriptionField;
            }
            set {
                this.responseCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public SONTXNSTODAYLISTTypeGSONTXNSTODAYLISTDetailType gSONTXNSTODAYLISTDetailType {
            get {
                return this.gSONTXNSTODAYLISTDetailTypeField;
            }
            set {
                this.gSONTXNSTODAYLISTDetailTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SONTXNSTODAYLISTTypeGSONTXNSTODAYLISTDetailType {
        
        private SONTXNSTODAYLISTTypeGSONTXNSTODAYLISTDetailTypeMSONTXNSTODAYLISTDetailType[] mSONTXNSTODAYLISTDetailTypeField;
        
        private string gField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mSONTXNSTODAYLISTDetailType")]
        public SONTXNSTODAYLISTTypeGSONTXNSTODAYLISTDetailTypeMSONTXNSTODAYLISTDetailType[] mSONTXNSTODAYLISTDetailType {
            get {
                return this.mSONTXNSTODAYLISTDetailTypeField;
            }
            set {
                this.mSONTXNSTODAYLISTDetailTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string g {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SONTXNSTODAYLISTTypeGSONTXNSTODAYLISTDetailTypeMSONTXNSTODAYLISTDetailType {
        
        private string accountNoField;
        
        private string bookingDateField;
        
        private string referenceField;
        
        private string descriptionField;
        
        private string valueDateField;
        
        private string withdrawalsField;
        
        private string depositsField;
        
        private string balanceField;
        
        private string mField;
        
        /// <remarks/>
        public string AccountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
            }
        }
        
        /// <remarks/>
        public string BookingDate {
            get {
                return this.bookingDateField;
            }
            set {
                this.bookingDateField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ValueDate {
            get {
                return this.valueDateField;
            }
            set {
                this.valueDateField = value;
            }
        }
        
        /// <remarks/>
        public string Withdrawals {
            get {
                return this.withdrawalsField;
            }
            set {
                this.withdrawalsField = value;
            }
        }
        
        /// <remarks/>
        public string Deposits {
            get {
                return this.depositsField;
            }
            set {
                this.depositsField = value;
            }
        }
        
        /// <remarks/>
        public string Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string m {
            get {
                return this.mField;
            }
            set {
                this.mField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StmtTodayRequest {
        
        private string organizationCodeField;
        
        private string branchCodeField;
        
        private string productCodeField;
        
        private string schemeCodeField;
        
        private string accountNumberField;
        
        /// <remarks/>
        public string OrganizationCode {
            get {
                return this.organizationCodeField;
            }
            set {
                this.organizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SchemeCode {
            get {
                return this.schemeCodeField;
            }
            set {
                this.schemeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransactionStatusResponse {
        
        private string responseCodeField;
        
        private string responseCodeDescriptionField;
        
        private string statusField;
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeDescription {
            get {
                return this.responseCodeDescriptionField;
            }
            set {
                this.responseCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransactionStatusRequest {
        
        private string sTANField;
        
        /// <remarks/>
        public string STAN {
            get {
                return this.sTANField;
            }
            set {
                this.sTANField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransactionInfoResponse {
        
        private string responseCodeField;
        
        private string responseCodeDescriptionField;
        
        private System.DateTime transactionDateField;
        
        private string transactionBranchCodeField;
        
        private string sTANField;
        
        private string transactionRefNoField;
        
        private string transactionIdentificationNoField;
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeDescription {
            get {
                return this.responseCodeDescriptionField;
            }
            set {
                this.responseCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionBranchCode {
            get {
                return this.transactionBranchCodeField;
            }
            set {
                this.transactionBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string STAN {
            get {
                return this.sTANField;
            }
            set {
                this.sTANField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionRefNo {
            get {
                return this.transactionRefNoField;
            }
            set {
                this.transactionRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionIdentificationNo {
            get {
                return this.transactionIdentificationNoField;
            }
            set {
                this.transactionIdentificationNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransactionInfoRequest {
        
        private string organizationCodeField;
        
        private System.DateTime transactionDateField;
        
        private string transactionBranchCodeField;
        
        private string sTANField;
        
        private string transactionRefNoField;
        
        private string transactionTypeField;
        
        private string voucherTypeField;
        
        private string systemCodeField;
        
        private string customerAccountTypeField;
        
        private string drCustomerBranchCodeField;
        
        private string drCustomerProductCodeField;
        
        private string drCustomerSchemeCodeField;
        
        private string drCustomerAccountNumberField;
        
        private string crCustomerBranchCodeField;
        
        private string crCustomerProductCodeField;
        
        private string crCustomerSchemeCodeField;
        
        private string crCustomerAccountNumberField;
        
        private string drGLAccountField;
        
        private string crGLAccountField;
        
        private string instrumentTypeField;
        
        private string instrumentNoField;
        
        private System.DateTime instrumentDateField;
        
        private bool instrumentDateFieldSpecified;
        
        private decimal transactionAmountField;
        
        private string transactionNarrationField;
        
        private string isReversalField;
        
        private int orginatingTranIdentNoField;
        
        private string currencyField;
        
        private string authorizationField;
        
        private string payeeNameField;
        
        /// <remarks/>
        public string OrganizationCode {
            get {
                return this.organizationCodeField;
            }
            set {
                this.organizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionBranchCode {
            get {
                return this.transactionBranchCodeField;
            }
            set {
                this.transactionBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string STAN {
            get {
                return this.sTANField;
            }
            set {
                this.sTANField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionRefNo {
            get {
                return this.transactionRefNoField;
            }
            set {
                this.transactionRefNoField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string VoucherType {
            get {
                return this.voucherTypeField;
            }
            set {
                this.voucherTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SystemCode {
            get {
                return this.systemCodeField;
            }
            set {
                this.systemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerAccountType {
            get {
                return this.customerAccountTypeField;
            }
            set {
                this.customerAccountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DrCustomerBranchCode {
            get {
                return this.drCustomerBranchCodeField;
            }
            set {
                this.drCustomerBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DrCustomerProductCode {
            get {
                return this.drCustomerProductCodeField;
            }
            set {
                this.drCustomerProductCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DrCustomerSchemeCode {
            get {
                return this.drCustomerSchemeCodeField;
            }
            set {
                this.drCustomerSchemeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DrCustomerAccountNumber {
            get {
                return this.drCustomerAccountNumberField;
            }
            set {
                this.drCustomerAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CrCustomerBranchCode {
            get {
                return this.crCustomerBranchCodeField;
            }
            set {
                this.crCustomerBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CrCustomerProductCode {
            get {
                return this.crCustomerProductCodeField;
            }
            set {
                this.crCustomerProductCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CrCustomerSchemeCode {
            get {
                return this.crCustomerSchemeCodeField;
            }
            set {
                this.crCustomerSchemeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CrCustomerAccountNumber {
            get {
                return this.crCustomerAccountNumberField;
            }
            set {
                this.crCustomerAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DrGLAccount {
            get {
                return this.drGLAccountField;
            }
            set {
                this.drGLAccountField = value;
            }
        }
        
        /// <remarks/>
        public string CrGLAccount {
            get {
                return this.crGLAccountField;
            }
            set {
                this.crGLAccountField = value;
            }
        }
        
        /// <remarks/>
        public string InstrumentType {
            get {
                return this.instrumentTypeField;
            }
            set {
                this.instrumentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string InstrumentNo {
            get {
                return this.instrumentNoField;
            }
            set {
                this.instrumentNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InstrumentDate {
            get {
                return this.instrumentDateField;
            }
            set {
                this.instrumentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstrumentDateSpecified {
            get {
                return this.instrumentDateFieldSpecified;
            }
            set {
                this.instrumentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TransactionAmount {
            get {
                return this.transactionAmountField;
            }
            set {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionNarration {
            get {
                return this.transactionNarrationField;
            }
            set {
                this.transactionNarrationField = value;
            }
        }
        
        /// <remarks/>
        public string IsReversal {
            get {
                return this.isReversalField;
            }
            set {
                this.isReversalField = value;
            }
        }
        
        /// <remarks/>
        public int OrginatingTranIdentNo {
            get {
                return this.orginatingTranIdentNoField;
            }
            set {
                this.orginatingTranIdentNoField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string Authorization {
            get {
                return this.authorizationField;
            }
            set {
                this.authorizationField = value;
            }
        }
        
        /// <remarks/>
        public string PayeeName {
            get {
                return this.payeeNameField;
            }
            set {
                this.payeeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EODStatusReponse {
        
        private string responseCodeField;
        
        private string responseCodeDescriptionField;
        
        private string eODStatusField;
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeDescription {
            get {
                return this.responseCodeDescriptionField;
            }
            set {
                this.responseCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string EODStatus {
            get {
                return this.eODStatusField;
            }
            set {
                this.eODStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountInfoResponse {
        
        private string responseCodeField;
        
        private string responseCodeDescriptionField;
        
        private string organizationCodeField;
        
        private string accountCategoryField;
        
        private string branchCodeField;
        
        private string productCodeField;
        
        private string schemeCodeField;
        
        private string accountIDField;
        
        private string accountNumberField;
        
        private string accountTitleField;
        
        private string accountStatusField;
        
        private System.DateTime accountOpeningDateField;
        
        private string accountCurrencyField;
        
        private string accountBranchCodeField;
        
        private decimal availableBalanceField;
        
        private string[] accountRestraintsField;
        
        private string identificationNoField;
        
        private string customerIDField;
        
        private string accountNatureField;
        
        private string offPhoneField;
        
        private string accountPhoneField;
        
        private string accountAddressField;
        
        private string accountMobileField;
        
        private string legacyAcNoField;
        
        private string sDNAccountNoField;
        
        private string sDNIBANField;
        
        private string t24IBANField;
        
        private string t24ACNOField;
        
        private string aCALTID5Field;
        
        private string aCALTID6Field;
        
        private string compNameField;
        
        private string categoryDescField;
        
        private string sectorDescField;
        
        /// <remarks/>
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeDescription {
            get {
                return this.responseCodeDescriptionField;
            }
            set {
                this.responseCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationCode {
            get {
                return this.organizationCodeField;
            }
            set {
                this.organizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCategory {
            get {
                return this.accountCategoryField;
            }
            set {
                this.accountCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SchemeCode {
            get {
                return this.schemeCodeField;
            }
            set {
                this.schemeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AccountTitle {
            get {
                return this.accountTitleField;
            }
            set {
                this.accountTitleField = value;
            }
        }
        
        /// <remarks/>
        public string AccountStatus {
            get {
                return this.accountStatusField;
            }
            set {
                this.accountStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AccountOpeningDate {
            get {
                return this.accountOpeningDateField;
            }
            set {
                this.accountOpeningDateField = value;
            }
        }
        
        /// <remarks/>
        public string AccountCurrency {
            get {
                return this.accountCurrencyField;
            }
            set {
                this.accountCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string AccountBranchCode {
            get {
                return this.accountBranchCodeField;
            }
            set {
                this.accountBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal AvailableBalance {
            get {
                return this.availableBalanceField;
            }
            set {
                this.availableBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string[] AccountRestraints {
            get {
                return this.accountRestraintsField;
            }
            set {
                this.accountRestraintsField = value;
            }
        }
        
        /// <remarks/>
        public string IdentificationNo {
            get {
                return this.identificationNoField;
            }
            set {
                this.identificationNoField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNature {
            get {
                return this.accountNatureField;
            }
            set {
                this.accountNatureField = value;
            }
        }
        
        /// <remarks/>
        public string OffPhone {
            get {
                return this.offPhoneField;
            }
            set {
                this.offPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string AccountPhone {
            get {
                return this.accountPhoneField;
            }
            set {
                this.accountPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string AccountAddress {
            get {
                return this.accountAddressField;
            }
            set {
                this.accountAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AccountMobile {
            get {
                return this.accountMobileField;
            }
            set {
                this.accountMobileField = value;
            }
        }
        
        /// <remarks/>
        public string LegacyAcNo {
            get {
                return this.legacyAcNoField;
            }
            set {
                this.legacyAcNoField = value;
            }
        }
        
        /// <remarks/>
        public string SDNAccountNo {
            get {
                return this.sDNAccountNoField;
            }
            set {
                this.sDNAccountNoField = value;
            }
        }
        
        /// <remarks/>
        public string SDNIBAN {
            get {
                return this.sDNIBANField;
            }
            set {
                this.sDNIBANField = value;
            }
        }
        
        /// <remarks/>
        public string T24IBAN {
            get {
                return this.t24IBANField;
            }
            set {
                this.t24IBANField = value;
            }
        }
        
        /// <remarks/>
        public string T24ACNO {
            get {
                return this.t24ACNOField;
            }
            set {
                this.t24ACNOField = value;
            }
        }
        
        /// <remarks/>
        public string ACALTID5 {
            get {
                return this.aCALTID5Field;
            }
            set {
                this.aCALTID5Field = value;
            }
        }
        
        /// <remarks/>
        public string ACALTID6 {
            get {
                return this.aCALTID6Field;
            }
            set {
                this.aCALTID6Field = value;
            }
        }
        
        /// <remarks/>
        public string CompName {
            get {
                return this.compNameField;
            }
            set {
                this.compNameField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryDesc {
            get {
                return this.categoryDescField;
            }
            set {
                this.categoryDescField = value;
            }
        }
        
        /// <remarks/>
        public string SectorDesc {
            get {
                return this.sectorDescField;
            }
            set {
                this.sectorDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountInfoRequest {
        
        private string organizationCodeField;
        
        private string branchCodeField;
        
        private string productCodeField;
        
        private string schemeCodeField;
        
        private string accountNumberField;
        
        /// <remarks/>
        public string OrganizationCode {
            get {
                return this.organizationCodeField;
            }
            set {
                this.organizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SchemeCode {
            get {
                return this.schemeCodeField;
            }
            set {
                this.schemeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetStatementToday {
        
        private StmtTodayRequest statementTodayRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StmtTodayRequest StatementTodayRequest {
            get {
                return this.statementTodayRequestField;
            }
            set {
                this.statementTodayRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class GetStatementTodayResponse {
        
        private SONTXNSTODAYLISTType statementTodayResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SONTXNSTODAYLISTType StatementTodayResponse {
            get {
                return this.statementTodayResponseField;
            }
            set {
                this.statementTodayResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void FetchAccountInfoCompletedEventHandler(object sender, FetchAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountInfoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetEODStatusCompletedEventHandler(object sender, GetEODStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEODStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEODStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EODStatusReponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EODStatusReponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DoTransactionsCompletedEventHandler(object sender, DoTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionInfoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetTransactionStatusCompletedEventHandler(object sender, GetTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionStatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetStatementTodayCompletedEventHandler(object sender, GetStatementTodayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatementTodayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatementTodayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetStatementTodayResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetStatementTodayResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591